apiVersion: v1
kind: ReplicationController
metadata:
  name: apache
spec:
  replicas: ${REPLICAS}
  selector:
    os: httpd
  template:
    metadata:
      labels:
        os: httpd
    spec:
      restartPolicy: Always
      containers:
      - name: apache
        image: httpd
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: Always
