apiVersion: v1
kind: ReplicationController
metadata:
  name: centos
spec:
  replicas: ${REPLICAS}
  selector:
    os: centos
  template:
    metadata:
      labels:
        os: centos
    spec:
      restartPolicy: Always
      containers:
      - name: centos
        image: centos
        command:
          - sleep
          - "360"
        imagePullPolicy: Always
