apiVersion: v1
kind: Service
metadata:
  name: centos
spec:
  ports:
  - port: ${SERVICE_PORT}
    targetPort: 5672
  selector:
    provider: centos



apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  ports:
  - port: 80      # service port
    protocol: TCP
  selector:
    app: nginx

        ports:
        - containerPort: 8080
          hostPort: 8080