apiVersion: v1
kind: ReplicationController
metadata:
  name: centos
  labels:
    provider: centos
    heritage: helm
spec:
  replicas: ${REPLICAS}
  template:
    metadata:
      labels:
        provider: centos
    spec:
      containers:
      - name: centos
        image: centos:7
        ports:
        - containerPort: 5672
