apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd
spec:
  replicas: ${REPLICAS}
  selector:
    os: httpd
  template:
    metadata:
      labels:
        os: httpd
    spec:
      restartPolicy: Always
      containers:
      - name: Apache
        image: httpd
        imagePullPolicy: Always
