.catalog:
  name: Apache
  version: 2.4
  description: Base Apache web server image
  questions:
    - variable: REPLICAS
      default: 1
      min: 1
      max: 10
      label: Server Replicas
      description: Initial number of server replicas
      required: true
      type: int
