.catalog:
  name: "Wordpress"
  version: 4.4-apache
  description: "Blog tool, publishing platform and CMS"
  minimum_rancher_version: v0.51.0
  questions:
    - variable: cluster_name
      description: "WordPress Cluster Name"
      label: "Cluster Name"
      required: true
      default: "default"
      type: "string"
    - variable: wordpress_replicas
      default: 1
      min: 1
      max: 100
      label: "WordPress Replicas"
      description: "Initial number of WordPress replicas"
      required: true
      type: int
    - variable: wordpress_port
      description: "HTTP port to access WordPress"
      label: "WordPress Port"
      required: true
      default: "80"
      type: "int"
    - variable: admin_username
      description: "MySQL Admin Username"
      label: "Admin Username for WordPress"
      required: true
      default: "admin"
      type: "string"
    - variable: admin_password
      description: "MySQL Admin Password"
      label: "Admin Password for WordPress"
      required: true
      default: "password"
      type: "string"
    - variable: nfs_server_ip
      description: "NFS Server IP Address"
      label: "NFS Server IP Address"
      required: true
      default: "10.5.36.50"
      type: "string"
