.catalog:
  name: "Wordpress"
  version: 7
  description: "Blog tool, publishing platform and CMS"
  uuid: Wordpress-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: cluster_name
      description: "WordPress Cluster Name"
      label: "Cluster Name"
      required: true
      default: "default"
      type: "string"
    - variable: wordpress_replicas
      default: 1
      min: 1
      max: 100
      label: "WordPress Replicas"
      description: "Initial number of WordPress replicas"
      required: true
      type: int
    - variable: http_port
      description: "http port to access Grafana"
      label: "Http Port"
      required: true
      default: "3000"
      type: "int"
    - variable: admin_username
      description: "MySQL Admin Username"
      label: "Admin Username"
      required: true
      default: "admin"
      type: "string"
    - variable: admin_password
      description: "MySQL Admin Password"
      label: "Admin Password"
      required: true
      default: "password"
      type: "string"
